export type Styles = {
  paddingInlineStart?: string;
  paddingInlineEnd?: string;
  paddingBlockStart?: string;
  paddingBlockEnd?: string;
  padding?: string;
  marginInlineStart?: string;
  marginInlineEnd?: string;
  marginBlockStart?: string;
  marginBlockEnd?: string;
  margin?: string;
  position?: string;
  top?: string;
  right?: string;
  bottom?: string;
  left?: string;
  display?: string;
  flexDirection?: string;
  justifyContent?: string;
  alignItems?: string;
  flexWrap?: string;
  gap?: string;
  width?: string;
  height?: string;
  backgroundColor?: string;
  color?: string;
  fontSize?: string;
  fontWeight?: string;
  border?: string;
  borderRadius?: string;
  cursor?: string;
  zIndex?: string;
  overflow?: string;
  boxShadow?: string;
  transform?: string;
  transition?: string;
  opacity?: string;
};

export const stylesObject: Styles = {};
